// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxqhs0hFs4J6EWCxdkHXbk5MmHy4K59Z8',
    appId: '1:921220430665:web:3c9d202d5bdabd9bfe3898',
    messagingSenderId: '921220430665',
    projectId: 'fatima-6d75d',
    authDomain: 'fatima-6d75d.firebaseapp.com',
    storageBucket: 'fatima-6d75d.firebasestorage.app',
    measurementId: 'G-BHJB7D7JJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEwqHTTMFW2eqC_QBDIb0j31bWN4c0A6E',
    appId: '1:921220430665:android:2d8d3e07829a6b13fe3898',
    messagingSenderId: '921220430665',
    projectId: 'fatima-6d75d',
    storageBucket: 'fatima-6d75d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVFwYe3NJM9hpxXh5EHGtGRH8LKT6TsU',
    appId: '1:921220430665:ios:88d36eecaaf54fcbfe3898',
    messagingSenderId: '921220430665',
    projectId: 'fatima-6d75d',
    storageBucket: 'fatima-6d75d.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVFwYe3NJM9hpxXh5EHGtGRH8LKT6TsU',
    appId: '1:921220430665:ios:88d36eecaaf54fcbfe3898',
    messagingSenderId: '921220430665',
    projectId: 'fatima-6d75d',
    storageBucket: 'fatima-6d75d.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}